In [1]:
import torch
from torch import nn

In [2]:
a = torch.ones(4, requires_grad=True)
b = torch.ones(4, requires_grad=True)
w = a.mean()
y = b.mean()
z = a.mean() + b.mean().detach()
opt1 = torch.optim.SGD([a], lr=1)
opt2 = torch.optim.SGD([b], lr=1)
opt3 = torch.optim.SGD([a, b], lr=1)
w.backward()
print('Now the gradients of a is {}'.format(a.grad))
opt2.step()
print('Now the value of a is {}, b is {}'.format(a, b))
y.backward()
print('Now the gradients of a is {}, b is {}'.format(a.grad, b.grad))
z.backward()
print('Now the gradients of a is {}, b is {}'.format(a.grad, b.grad))
opt3.step()
print('Now the value of a is {}, b is {}'.format(a, b))

Now the gradients of a is tensor([ 0.2500,  0.2500,  0.2500,  0.2500])
Now the value of a is tensor([ 1.,  1.,  1.,  1.]), b is tensor([ 1.,  1.,  1.,  1.])
Now the gradients of a is tensor([ 0.2500,  0.2500,  0.2500,  0.2500]), b is tensor([ 0.2500,  0.2500,  0.2500,  0.2500])
Now the gradients of a is tensor([ 0.5000,  0.5000,  0.5000,  0.5000]), b is tensor([ 0.2500,  0.2500,  0.2500,  0.2500])
Now the value of a is tensor([ 0.5000,  0.5000,  0.5000,  0.5000]), b is tensor([ 0.7500,  0.7500,  0.7500,  0.7500])


In [17]:
net = nn.Linear(4,1)
a = torch.ones(4, requires_grad=True)
w = net(a)
opt = torch.optim.SGD(net.parameters(), lr=0.01)
w.backward(retain_graph=True)
for param in net.parameters():
    print(param.grad)

tensor([[ 1.,  1.,  1.,  1.]])
tensor([ 1.])


In [18]:
opt.zero_grad()

In [19]:
w.backward()
for param in net.parameters():
    print(param.grad.data)

tensor([[ 1.,  1.,  1.,  1.]])
tensor([ 1.])
